
services:
  app:
    build: 
      dockerfile: dockerfile
      context: .
    ports:
      - "5000:5000"
      - "40000:40000"
  
    
    develop:
      watch:
        - action: rebuild
          path: .
          target: /app  
          
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: onlineshop
    depends_on:
      mysql:
        condition: service_healthy    

  mysql:
    image: mysql:8.0.33-oracle
    ports: 
     - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: onlineshop
    volumes:
      - mysql-data:/var/lib/mysql  
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s 

volumes:
  mysql-data:  
